add_newline = false
continuation_prompt = "[ï‘ ï‘ ](bright-black) "
format = """$fill \
      $status\
      $username\
      $hostname\
      $localip\
      $shlvl\
      $singularity\
      $kubernetes\
      $vcsh\
      $fossil_branch\
      $fossil_metrics\
      $git_branch\
      $git_commit\
      $git_state\
      $git_metrics\
      $git_status\
      $hg_branch\
      $pijul_channel\
      $docker_context\
      $package\
      $c\
      $cmake\
      $cobol\
      $cpp\
      $daml\
      $dart\
      $deno\
      $dotnet\
      $elixir\
      $elm\
      $erlang\
      $fennel\
      $gleam\
      $golang\
      $guix_shell\
      $haskell\
      $haxe\
      $helm\
      $java\
      $julia\
      $kotlin\
      $gradle\
      $lua\
      $nim\
      $nodejs\
      $ocaml\
      $opa\
      $perl\
      $php\
      $pulumi\
      $purescript\
      $python\
      $quarto\
      $raku\
      $rlang\
      $red\
      $ruby\
      $rust\
      $scala\
      $solidity\
      $swift\
      $terraform\
      $typst\
      $vlang\
      $vagrant\
      $zig\
      $buf\
      $nix_shell\
      $conda\
      $meson\
      $spack\
      $memory_usage\
      $aws\
      $gcloud\
      $openstack\
      $azure\
      $nats\
      $direnv\
      $env_var\
      $mise\
      $crystal\
      $custom\
      $sudo\
      $cmd_duration\
      $jobs\
      $battery\
      $time\
      $os\
      $container\
      $netns\
      $shell\
      $directory\
      $line_break\
      $character\
    """

[character] 
format = "$symbol "
success_symbol = "[](cyan)"
error_symbol = "[](red)"
vimcmd_symbol = "[](cyan)"
vimcmd_replace_symbol = "[<](yellow)"
vimcmd_replace_one_symbol = "[<](yellow)"
vimcmd_visual_symbol = "[<](magenta)"

[fill] 
symbol = "â”€"
style = "white"

[aws] 
format = "[$symbol($profile)(($region))( $duration)]($style) "
symbol = "îŒ½ "

[buf]
symbol = "ï’ "

[bun]
format = "[$symbol($version)]($style) "

[c] 
format = "[$symbol($version(-$name))]($style) "
symbol = "î˜ž "

[cmake]
format = "[$symbol($version)]($style) "
symbol = "îž” "

[cmd_duration]
format = "[ï€— $duration]($style) "

[cobol]
format = "[$symbol($version)]($style) "

[conda]
format = "[$symbol$environment]($style) "
symbol = "ï„Œ "

#[cpp]
# format = "[$symbol($version(-$name))]($style) "

[crystal]
format = "[$symbol($version)]($style)"
symbol = "î˜¯ "

[daml]
format = "[$symbol($version)]($style) "

[dart]
format = "[$symbol($version)]($style)"
symbol = "îž˜ "

[deno]
format = "[$symbol($version)]($style) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "green"
fish_style_pwd_dir_length = 1
read_only = " ó°Œ¾"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ïŒˆ "

[dotnet]
format = "[$symbol($version)(ðŸŽ¯ $tfm)]($style) "

[elixir]
format = "[$symbol($version (OTP $otp_version))]($style) "
symbol = "î˜­ "

[elm]
format = "[$symbol($version)]($style) "
symbol = "î˜¬ "

[erlang]
format = "[$symbol($version)]($style) "

[fennel]
format = "[$symbol($version)]($style) "
symbol = "îš¯ "

[fossil_branch]
format = "[$symbol$branch]($style) "
symbol = "ï˜ "

[gcloud]
format = "[$symbol$account(@$domain)(($region))]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ï˜ "
style = "cyan"

[git_commit]
tag_symbol = " ï’ "
style = "cyan"

[git_metrics]
format = "([$added]($added_style)/[$deleted]($deleted_style)) "
added_style = "green"
deleted_style = "red"
disabled = true

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "cyan"
conflicted = "[ï¡ ](red)"
ahead = "[ó°¶¼](yellow)"
behind = "[ó°¶¹](yellow)"
diverged = "[ó°¹¹](red)"
up_to_date = ""
untracked = "[î«œ ](green)"
stashed = "[îª˜ ](blue)"
modified = "[î«ž ](yellow)"
staged = "[ó°¦˜ ](blue)"
renamed = "[î«  ](yellow)"
deleted = "[î«Ÿ ](red)"
typechanged = ""

[golang]
format = "[$symbol($version)]($style) "
symbol = "î˜§ "

[gradle]
format = "[$symbol($version)]($style) "
symbol = "î™  "

[guix_shell]
format = "[$symbol]($style) "
symbol = "ïŒ¥ "

[haskell]
format = "[$symbol($version)]($style) "
symbol = "î· "

[haxe]
format = "[$symbol($version)]($style) "
symbol = "î™¦ "

[hg_branch]
format = "[$symbol$branch]($style) "
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
format = "[$symbol($version)]($style) "
symbol = "î‰– "

[jobs]
symbol = "ó±Œ£ "

[julia]
format = "[$symbol($version)]($style) "
symbol = "î˜¤ "

[kotlin]
format = "[$symbol($version)]($style) "
symbol = "î˜´ "

[kubernetes]
format = "[$symbol$context( ($namespace))]($style) "

[lua]
format = "[$symbol($version)]($style) "
symbol = "î˜  "

[memory_usage]
format = "$symbol[$ram( | $swap)]($style) "
symbol = "ó°› "

[meson]
format = "[$symbol$project]($style) "
symbol = "ó°”· "

[nim]
format = "[$symbol($version)]($style) "
symbol = "ó°†¥ "

[nix_shell]
format = "[$symbol$state( ($name))]($style) "
symbol = "ïŒ“ "

[nodejs]
format = "[$symbol($version)]($style) "
symbol = "îœ˜ "

[ocaml]
format = "[$symbol($version)(($switch_indicator$switch_name))]($style) "
symbol = "î™º "

[opa]
format = "[$symbol($version)]($style) "

[openstack]
format = "[$symbol$cloud(($project))]($style) "

[os]
format = "[$symbol]($style) "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠŽ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°žŒ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒŽ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ïŽ€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
format = "[$symbol$version]($style) "
symbol = "ó°— "

[perl]
format = "[$symbol($version)]($style) "
symbol = "î™¾ "

[php]
format = "[$symbol($version)]($style) "
symbol = "î˜ˆ "

[pijul_channel]
format = "[$symbol$channel]($style) "
symbol = "ï˜ "

#[pixi]
#format = "[$symbol$version( $environment)]($style) "

[pulumi]
format = "[$symbol$stack]($style) "

[purescript]
format = "[$symbol($version)]($style) "

[python]
format = "[$symbol$pyenv_prefix $version $virtualenv]($style) "
symbol = "îˆµ "

[raku]
format = "[$symbol($version-$vm_version)]($style) "

[red]
format = "[$symbol($version)]($style) "

[rlang]
symbol = "ó°Ÿ” "

[ruby]
format = "[$symbol($version)]($style) "
symbol = "îž‘ "

[rust]
format = "[$symbol($version)]($style) "
symbol = "ó±˜— "

[scala]
format = "[$symbol($version)]($style) "
symbol = "îœ· "

[solidity]
format = "[$symbol($version)]($style) "

[spack]
format = "[$symbol$environment]($style) "

[status]
format = "[$symbol$status]($style) "
symbol = "îª‡ "
disabled = false

[sudo]
format = "[as $symbol]($style) "

[swift]
format = "[$symbol($version)]($style) "
symbol = "î• "

[terraform]
format = "[$symbol$workspace]($style) "

[time]
format = "[$time]($style) "

[username]
format = "[$user]($style) "

[vagrant]
format = "[$symbol($version)]($style) "

[vlang]
format = "[$symbol($version)]($style) "

[zig]
format = "[$symbol($version)]($style) "
symbol = "îš© "
